controller_manager:
  ros__parameters:
    update_rate: 20.0
    use_sim_time: true

    tm5_900_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

tm5_900_arm_controller:
  ros__parameters:
    joints:
      - link1_joint
      - link2_joint
      - link3_joint
      - link4_joint
      - link5_joint
      - link6_joint
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      link1_joint:
        trajectory: 0.1
        goal: 0.05
      link2_joint:
        trajectory: 0.1
        goal: 0.05
      link3_joint:
        trajectory: 0.1
        goal: 0.05
      link4_joint:
        trajectory: 0.1
        goal: 0.05
      link5_joint:
        trajectory: 0.1
        goal: 0.05
      link6_joint:
        trajectory: 0.1
        goal: 0.05
